In [39]:
import scipy as sp
%matplotlib inline
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import kurtosis
from scipy.stats import skew

In [ ]:
# Randomly generate 1000 samples from normak distribution with mean=100, std=15

In [2]:
df=np.random.normal(100,15,1000)

In [ ]:
# Compute mean, median, and mode

In [23]:
mean=df.mean()
median=np.median(df)
std=df.std()

print("mean = {}".format(mean))
print("median = {}".format(median))
print("std = {}".format(std))

mean = 100.48522313247128
median = 100.36472964707426
std = 15.304348036207568


In [ ]:
# Compute min, max, Q1, Q3 and interquartile range

In [24]:
minn=df.min()
maxx=df.max()
Q1=np.quantile(df, .25)
Q3=np.quantile(df, .75)
IQR=Q3-Q1

print("min = {}".format(minn))
print("max = {}".format(maxx))
print("Q1 = {}".format(Q1))
print("Q3 = {}".format(Q3))
print("IQR = {}".format(IQR))

min = 48.9842747858987
max = 151.12768517782484
Q1 = 90.5245828193276
Q3 = 110.99821037714136
IQR = 20.473627557813757


In [ ]:
# Compute the variance and standard deviation

In [31]:
print("var =", np.var(df))
print("std =", np.std(df))

var = 234.22306881337042
std = 15.304348036207568


In [ ]:
# Compute the skewnes and kurtosis

In [28]:
print("skew : ", skew(df))
print("kurtosis : ", kurtosis(df))

skew :  -0.0013843974023419739
kurtosis :  -0.0011041812593122202


In [ ]:
# Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use np.arrange

In [32]:
x=np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# Then use np.array() to create a second array y containing 10 arbitrary integers.

In [33]:
y = np.array([1, 5, 7, 11, 13, 14, 14, 17, 20, 25])
y

array([ 1,  5,  7, 11, 13, 14, 14, 17, 20, 25])

In [ ]:
# Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [34]:
np.corrcoef(x, y)

array([[1.        , 0.97991377],
       [0.97991377, 1.        ]])

In [ ]:
# Run the code below

In [35]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [ ]:
# Call the relevant method to calculate Pearson's r correlation

In [37]:
x.corr(y)

0.7586402890911867

In [ ]:
# Call the relevant method to calculate Spearman's rho correlation

In [40]:
rho=stats.spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

In [ ]:
# Import Seaborn Library

In [43]:
import seaborn as sns

In [ ]:
# Load "tips" dataset from Seaborn

In [44]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'taxis',
 'tips',
 'titanic']

In [45]:
tips=sns.load_dataset("tips")

In [ ]:
# Generate descriptive statistics include those that summarize the central tendency, dispersion

In [48]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
# Call the relevant method to calculate pairwise Pearson's r correlation of 

In [49]:
tips.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000